services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: fastapi-auth
    environment:
      DATABASE_URL: postgresql+asyncpg://app:app@db:5432/inventorydb
    ports:
      - "8001:8000"
    depends_on:
      - db
  
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi-app
    environment:
      DATABASE_URL: postgresql+asyncpg://app:app@db:5432/inventorydb
    ports:
      - "8002:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: fastapi-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: inventorydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data

volumes:
  pgdata2:
